/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import controle.Cidade_DAO;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Cidade;

/**
 *
 * @author henri
 */
public class CidadeJFrame extends javax.swing.JFrame {
   
    DefaultTableModel modeloTabela = new DefaultTableModel(new Object[][]{}, 
        new Object[]{"ID", "nome", "Cidade"});
    /**
     * Creates new form CidadeJFrame
     */
    public CidadeJFrame() {
        initComponents();
        tblCidade.setModel(modeloTabela);
        tblCidade.removeColumn(tblCidade.getColumnModel().getColumn(2));
        carregarCidades();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        txtCidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCidade = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        txtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCidadeKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Cidades Cadastradas");

        tblCidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCidade);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Cidade");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRemover))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        int indiceLinha = tblCidade.getSelectedRow();
        if(indiceLinha != -1){
        Cidade selecionado = (Cidade) modeloTabela.getValueAt(indiceLinha, 2);
        Cidade_DAO dao = new Cidade_DAO();
        dao.excluir(selecionado);
        carregarCidades();
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void txtCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeKeyReleased
       // UF selecionado = (UF) boxUF.getSelectedItem();
        String nome = txtCidade.getText().trim().toLowerCase();
        carregarCidades(nome);
       /* if( selecionado != null){
           modeloTabela.setNumRows(0);
           Cidade_DAO dao = new Cidade_DAO();
           for(Cidade cid: dao.buscar(selecionado, nome)){
               modeloTabela.addRow(new Object[]{cid.getId(), 
               cid.getNome(),
               cid.getUf(),
               cid
               });
            }
        } else {
           modeloTabela.setNumRows(0);
           Cidade_DAO dao = new Cidade_DAO();
           for(Cidade cid: dao.buscar(nome)){
               modeloTabela.addRow(new Object[]{cid.getId(), 
               cid.getNome(),
               cid.getUf(),
               cid
               });
            }  */   
        
    }//GEN-LAST:event_txtCidadeKeyReleased

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        CadastroCid_JD telaCadastro = new CadastroCid_JD(this, rootPaneCheckingEnabled);
        telaCadastro.setVisible(true);
            Cidade novaCidade = telaCadastro.getCidade();
            if (novaCidade != null && novaCidade.getNome() != null) {
                Cidade_DAO dao = new Cidade_DAO();
                dao.inserir(novaCidade);
                carregarCidades();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao salvar Cidade");
            }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int indiceLinha = tblCidade.getSelectedRow();
        if(indiceLinha != -1)
        {
        Cidade selecionado = (Cidade) modeloTabela.getValueAt(indiceLinha, 2);
        CadastroCid_JD telaCadastro = new CadastroCid_JD(this, rootPaneCheckingEnabled);
        telaCadastro.setCidade(selecionado);
        telaCadastro.setVisible(true);
            if (selecionado != null && selecionado.getNome() != null) {
                Cidade_DAO dao = new Cidade_DAO();
                dao.editar(selecionado);
                carregarCidades();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao editar Cidade");
            }
        }    
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CidadeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CidadeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CidadeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CidadeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CidadeJFrame().setVisible(true);
            }
        });
    }
    
    public void carregarCidades(){

            modeloTabela.setNumRows(0);
            Cidade_DAO dao = new Cidade_DAO();
            ArrayList<Cidade> cidades = dao.buscar();
            for(Cidade cid: cidades){
                modeloTabela.addRow(new Object[]{cid.getId(), 
                cid.getNome(),
                cid 
                });
            }
        
        
        }
    
    public void carregarCidades(String nome) {
        modeloTabela.setNumRows(0);
        Cidade_DAO dao = new Cidade_DAO();
        ArrayList<Cidade> cidades = dao.buscar(nome);
        for(Cidade cid: cidades){
            modeloTabela.addRow(new Object[]{cid.getId(), 
            cid.getNome(),
            cid});
        }
    }
    
 /*   public void CarregarUfs(){
        boxUF.removeAllItems();
        Uf_DAO dao = new Uf_DAO();
        boxUF.addItem(null);
        for(UF u: dao.buscar()){
           boxUF.addItem(u);
        }
    
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCidade;
    private javax.swing.JTextField txtCidade;
    // End of variables declaration//GEN-END:variables
}
