/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.Medicamento_DAO;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Medicamento;

/**
 *
 * @author henri
 */
public class MedicamentoJFrame extends javax.swing.JFrame {
    
    DefaultListModel lista = new DefaultListModel();
    DefaultTableModel modeloTabela = new DefaultTableModel(new Object[][]{}, 
            new Object[]{"ID", "Nome", "Quantidade", "Medicamento"});

    /**
     * Creates new form MedicamentoJFrame
     */
    public MedicamentoJFrame() {
        initComponents();
        tblMedicamento.setModel(modeloTabela);
        tblMedicamento.removeColumn(tblMedicamento.getColumnModel().getColumn(3));
        carregarMedicamentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        txtMedicamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicamento = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Medicamento");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        txtMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicamentoActionPerformed(evt);
            }
        });
        txtMedicamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMedicamentoKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Medicamentos Cadastrados");

        tblMedicamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMedicamento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRemover))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        CadastroMedi_JD telaCadastro = new CadastroMedi_JD(this, rootPaneCheckingEnabled);
        telaCadastro.setVisible(true);
        Medicamento novo = telaCadastro.getMedicamento();
        if (novo != null && novo.getNome() != null && novo.getQnt() != null) {
            Medicamento_DAO dao = new Medicamento_DAO();
            dao.inserir(novo);
            carregarMedicamentos();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao salvar Medicamento");
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int indiceLinha = tblMedicamento.getSelectedRow();
        if(indiceLinha != -1)
        {
            Medicamento selecionado = (Medicamento) modeloTabela.getValueAt(indiceLinha, 3);
            CadastroMedi_JD telaCadastro = new CadastroMedi_JD(this, rootPaneCheckingEnabled);
            telaCadastro.setMedicamento(selecionado);
            telaCadastro.setVisible(true);
            if (selecionado != null && selecionado.getNome() != null && selecionado.getQnt() != null) {
                Medicamento_DAO dao = new Medicamento_DAO();
                dao.editar(selecionado);
                carregarMedicamentos();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao editar Medicamento");
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        int indiceLinha = tblMedicamento.getSelectedRow();
        if(indiceLinha != -1){
            Medicamento selecionado = (Medicamento) modeloTabela.getValueAt(indiceLinha, 3);
            Medicamento_DAO dao = new Medicamento_DAO();
            dao.excluir(selecionado);
            carregarMedicamentos();
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void txtMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicamentoActionPerformed

    private void txtMedicamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedicamentoKeyReleased
        // UF selecionado = (UF) boxUF.getSelectedItem();
        String nome = txtMedicamento.getText().trim().toLowerCase();
        carregarMedicamentos(nome);
        /* if( selecionado != null){
            modeloTabela.setNumRows(0);
            Cidade_DAO dao = new Cidade_DAO();
            for(Cidade cid: dao.buscar(selecionado, nome)){
                modeloTabela.addRow(new Object[]{cid.getId(),
                    cid.getNome(),
                    cid.getUf(),
                    cid
                });
            }
        } else {
            modeloTabela.setNumRows(0);
            Cidade_DAO dao = new Cidade_DAO();
            for(Cidade cid: dao.buscar(nome)){
                modeloTabela.addRow(new Object[]{cid.getId(),
                    cid.getNome(),
                    cid.getUf(),
                    cid
                });
            }  */
    }//GEN-LAST:event_txtMedicamentoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicamentoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicamentoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicamentoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicamentoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicamentoJFrame().setVisible(true);
            }
        });
    }
    
    public void carregarMedicamentos(){

        modeloTabela.setNumRows(0);
        Medicamento_DAO dao = new Medicamento_DAO();
        ArrayList<Medicamento> medicamentos = dao.buscar();
        for(Medicamento medi: medicamentos){
            modeloTabela.addRow(new Object[]{medi.getId(), 
            medi.getNome(),
            medi.getQnt(),
            medi 
            });
            }
        }
    
    public void carregarMedicamentos(String nome) {
            
        modeloTabela.setNumRows(0);
        Medicamento_DAO dao = new Medicamento_DAO();
        ArrayList<Medicamento> medicamentos = dao.buscar(nome);
        for(Medicamento medi: medicamentos){
            modeloTabela.addRow(new Object[]{medi.getId(), 
            medi.getNome(),
            medi.getQnt(),
            medi 
            });
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMedicamento;
    private javax.swing.JTextField txtMedicamento;
    // End of variables declaration//GEN-END:variables
}
