/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


/**
 *
 * @author Vanessa-NB
 */
public class PrincipalJFrame extends javax.swing.JFrame {
//    Uf_DAO daoUF = new Uf_DAO();

    /**
     * Creates new form PrincipalJFrame
     */
    public PrincipalJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAreaTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mHospital = new javax.swing.JMenu();
        menCid = new javax.swing.JMenuItem();
        menMedico = new javax.swing.JMenuItem();
        menMedicamento = new javax.swing.JMenuItem();
        menPaciente = new javax.swing.JMenuItem();
        menInt = new javax.swing.JMenuItem();
        mAjuda = new javax.swing.JMenu();
        miSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jAreaTrabalhoLayout = new javax.swing.GroupLayout(jAreaTrabalho);
        jAreaTrabalho.setLayout(jAreaTrabalhoLayout);
        jAreaTrabalhoLayout.setHorizontalGroup(
            jAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );
        jAreaTrabalhoLayout.setVerticalGroup(
            jAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        mHospital.setText("Sistema");

        menCid.setText("Cidade");
        menCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCidActionPerformed(evt);
            }
        });
        mHospital.add(menCid);

        menMedico.setText("Médico");
        menMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menMedicoActionPerformed(evt);
            }
        });
        mHospital.add(menMedico);

        menMedicamento.setText("Medicamento");
        menMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menMedicamentoActionPerformed(evt);
            }
        });
        mHospital.add(menMedicamento);

        menPaciente.setText("Paciente");
        menPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menPacienteActionPerformed(evt);
            }
        });
        mHospital.add(menPaciente);

        menInt.setText("Internação");
        menInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menIntActionPerformed(evt);
            }
        });
        mHospital.add(menInt);

        jMenuBar1.add(mHospital);

        mAjuda.setText("Ajuda");

        miSobre.setText("Sobre");
        miSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSobreActionPerformed(evt);
            }
        });
        mAjuda.add(miSobre);

        jMenuBar1.add(mAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaTrabalho)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaTrabalho)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSobreActionPerformed
        SobreJDialog telaSobre = new SobreJDialog(this, rootPaneCheckingEnabled);
        telaSobre.setVisible(true);
    }//GEN-LAST:event_miSobreActionPerformed

    private void menCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCidActionPerformed
 
        CidadeJFrame telaCid = new CidadeJFrame();
        telaCid.setVisible(true);
    }//GEN-LAST:event_menCidActionPerformed

    private void menMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menMedicoActionPerformed
        
        MedJFrame telaMed = new MedJFrame();
        telaMed.setVisible(true);
    }//GEN-LAST:event_menMedicoActionPerformed

    private void menMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menMedicamentoActionPerformed
        
        MedicamentoJFrame telaMedi = new MedicamentoJFrame();
        telaMedi.setVisible(true);
        
    }//GEN-LAST:event_menMedicamentoActionPerformed

    private void menPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menPacienteActionPerformed
        
        PacienteJFrame telaPac = new PacienteJFrame();
        telaPac.setVisible(true);
    }//GEN-LAST:event_menPacienteActionPerformed

    private void menIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menIntActionPerformed
        
        InternacaoJFrame telaInt = new InternacaoJFrame();
        telaInt.setVisible(true);
    }//GEN-LAST:event_menIntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jAreaTrabalho;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mAjuda;
    private javax.swing.JMenu mHospital;
    private javax.swing.JMenuItem menCid;
    private javax.swing.JMenuItem menInt;
    private javax.swing.JMenuItem menMedicamento;
    private javax.swing.JMenuItem menMedico;
    private javax.swing.JMenuItem menPaciente;
    private javax.swing.JMenuItem miSobre;
    // End of variables declaration//GEN-END:variables
}
